FROM ubuntu:24.04

LABEL org.opencontainers.image.authors="Badr @pythops"

# Define the BSP version
ARG BSP=https://developer.nvidia.com/downloads/embedded/L4T/r39_Release_v2.0/release/Jetson_Linux_R39.2.0_aarch64.tbz2

ARG L4T_PACKAGES

# Install different dependencies
RUN apt update && \
    apt install -y \
        wget \
        patch \
        bzip2 \
        qemu-user-static \
        sudo \
        libxml2-utils \
        python3 \
        gdisk \
        kpartx \
        cpio \
        binutils \
        ssh \
        python-is-python3 \
        dosfstools \
        python3-yaml \
        build-essential \
        lz4 \
        cpio \
        xmlstarlet

# Extract the BSP
RUN mkdir /build && \
    wget -qO- $BSP | tar -jxpf - -C /build

# Copy the ubuntu rootfs
COPY rootfs/ /build/Linux_for_Tegra/rootfs/

# Sudo permissions
# RUN chmod 4755 /build/Linux_for_Tegra/rootfs/usr/bin/sudo


# Install nvidia packages in the new rootfs
WORKDIR /build/Linux_for_Tegra/
RUN ./apply_binaries.sh

# Fix permissions
RUN chroot /build/Linux_for_Tegra/rootfs/ /bin/bash -c "chown -R jetson:jetson /home/jetson && chmod 1777 /tmp"

# L4T packages
RUN mount -t proc proc rootfs/proc/ && \
    mount -t sysfs sys rootfs/sys && \
    mount -o bind /dev rootfs/dev && \
    chroot rootfs /bin/bash -c "echo 'nameserver 8.8.8.8' > /etc/resolv.conf && apt update; apt install -y cuda-toolkit $L4T_PACKAGES"

# Edit initrd
WORKDIR /tmp/pythops
RUN gzip -d -c /build/Linux_for_Tegra/bootloader/l4t_initrd.img > initrd
WORKDIR /tmp/pythops/lab
RUN cpio -iv < ../initrd && \
    echo "nameserver 127.0.0.53" > etc/resolv.conf && \
    find . | cpio --create --format="newc" > ../new_initrd
WORKDIR /tmp/pythops
RUN gzip new_initrd && mv new_initrd.gz /build/Linux_for_Tegra/bootloader/l4t_initrd.img

# Copy the script to create the image
COPY scripts/create-jetson-image.sh /usr/local/bin/

WORKDIR /build/Linux_for_Tegra/tools
