# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "../", "/jetson-nano-image"
  config.vm.define "jetson" do |jetson|
    jetson.vm.hostname = "jetson"
    jetson.vm.provider "virtualbox" do |vb|
		  vb.name = "jetson"
		  vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
	end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yaml"
  end

end
